### ISSUE TITLE
Pass commit message parameter to deploy task

### ISSUE THREAD

**Issue by pmalek** [bespokejs/generator-bespoke#17]
I have seen that https://github.com/tschaub/grunt-gh-pages has parameter for commit message 

```
--gh-pages-message 'Tagging v1.2.3'
```

Can we introduce the same in `generator-bespoke`? To pass the parameter from `grunt deploy` in generator to `grunt-gh-pages`

**Comment by hsablonniere** [comment]
Hi @pmalek.

Are you still interested by this? How would you pass the commit message on deploy? Would you maybe set some kind of pattern?

**Comment by pmalek** [comment]
@hsablonniere I am sorry but I don't even remember using this tool not mentioning HOW to use it and what kind of problems it caused me. I believe you can close this now.
