### ISSUE TITLE
failed to locate prism/themes/prism-okaidia.css when starting from no pre-made theme

### ISSUE THREAD

**Issue by nuthinking** [bespokejs/generator-bespoke#30]
If I create a presentation without a pre-made theme, main.styl contains a reference to prism-okaidia.css and, because this file is not available, it throws the following error.

    [17:16:07] Plumber found unhandled error:
     Error in plugin 'gulp-stylus'
    Message:
        /Users/christiangiordano/Documents/Barclays/Visual Language/presentations/barclays-body-language/src/styles/main.styl:9:9
        5| // thanks to Stylus' "import css" and "paths" options
        6| 
        7| @import 'normalizecss/normalize.css'
        8| 
        9| @import 'prism/themes/prism-okaidia.css'
    --------------^
       10| // Check out "bower_components/prism/themes/" for available themes
       11| 
       12| // Style using Bespoke Classes: https://github.com/markdalgleish/bespoke-classes
    
    failed to locate @import file prism/themes/prism-okaidia.css

The main.styl starts with:

    // New to Stylus? Check out http://learnboost.github.io/stylus
    // Use modern CSS thanks to Autoprefixer: https://github.com/ai/autoprefixer
    
    // Import CSS from "node_modules" and "bower_components"
    // thanks to Stylus' "import css" and "paths" options
    
    @import 'normalizecss/normalize.css'
    
    @import 'prism/themes/prism-okaidia.css'
    // Check out "bower_components/prism/themes/" for available themes
    
    // Style using Bespoke Classes: https://github.com/markdalgleish/bespoke-classes
    
    .bespoke-parent
    ...

**Comment by hsablonniere** [comment]
Hi @nuthinking.

I'm working on a new version of the plugin, you can find out more in the roadmap here #36 and see the **Work in Progress** in the [v3 branch](https://github.com/bespokejs/generator-bespoke/tree/v3).

You problem should be fixed in v3 that's why I'm closing the issue. Let me know if you have time to try.
