### ISSUE TITLE
gulp-browserify is no longer maintained

### ISSUE THREAD

**Issue by aleung** [bespokejs/generator-bespoke#31]
[gulp-browserify](https://github.com/deepak1556/gulp-browserify) is no longer maintained. It depends on browserify 3.x which is very old version.

**Comment by hsablonniere** [comment]
Hey @aleung.

Thanks for the issue. I've tracked this in the v3 roadmap #36.

**Comment by hsablonniere** [comment]
It's now fixed in the v3 branch in #36.

**Comment by mojavelinux** [comment]
Nice work. I think we should keep the issue open until #36 is merged. We can, however, set the milestone so that we know when to close it.

**Comment by mojavelinux** [comment]
The generator now uses the latest version of the main browserify library.
