### ISSUE TITLE
PrismJS is on npm now

### ISSUE THREAD

**Issue by strugee** [bespokejs/generator-bespoke#32]
If we switch to the npm version, that means we can simplify stuff by nuking debowerify.

**Comment by lbearl** [comment]
Just FYI, I've submitted a PR for this

**Comment by hsablonniere** [comment]
Hi @strugee and @lbearl.

I'm closing this issue. You can find more explanations in #34 and see that we will address this problem in the new version of the generator in #36.

Thanks for your time :smile:.
