### ISSUE TITLE
Give the possibility to generate index.html instead of Jade file

### ISSUE THREAD

**Issue by Gillespie59** [bespokejs/generator-bespoke#35]
I have created my first bespokejs app via this generator. And I was quiet sad to see a Jade file for writing our slides. I dislike this syntax, and I would prefer to use HTML. 
We can add a parameter to Yeoman, in order to ask to the user which syntax he wants to use. 
What do you think ?

**Comment by hsablonniere** [comment]
This is tracked in new version #36.

**Comment by mojavelinux** [comment]
I agree :100:% ! In fact, @hsablonniere and I arrived at the same conclusion when we were discussing plans to revive the generator.

As Hubert mentions in #36, we're also going to add the option for writing slides in AsciiDoc (similar to Markdown, but more suitable for this purpose). That way, we give everyone a chance to compose slides in the format that is most comfortable to them (HTML, Pug/Jade or AsciiDoc).

**Comment by hsablonniere** [comment]
@Gillespie59 It's fixed in #36. I'm closing this issue. Let us know if you can test the v3 branch.

**Comment by Gillespie59** [comment]
Thanks. I will give the v3 a try asap.

**Comment by mojavelinux** [comment]
This is implemented in 3.0.0.

**Comment by Gillespie59** [comment]
Thanks :)
