### ISSUE TITLE
Generate a README.adoc when the user chose AsciiDoc as a templating engine

### ISSUE THREAD

**Issue by hsablonniere** [bespokejs/generator-bespoke#42]
Open questions :

* Is this a problem that NPM won't recognize README.adoc?
* Do we maintain 2 two files a markdown version for HTML and Pug and another for AsciiDoc or do we have another solution? (we already have 3 very similar index templates).

**Comment by mojavelinux** [comment]
> Is this a problem that NPM won't recognize README.adoc?

Given that we are generating a presentation published to gh-pages, not a node module published to npm, I don't think this matters at all.

> Do we maintain 2 two files a markdown version for HTML and Pug and another for AsciiDoc or do we have another solution?

I really wouldn't be opposed to just switching to AsciiDoc in all cases. After all, the point of the README is to render instructions on GitHub...and AsciiDoc handles that just fine (arguably better).

However, if we decide we only want AsciiDoc README when choosing an AsciiDoc-based presentation, I think we only need to maintain two files (README.md and README.adoc).

**Comment by hsablonniere** [comment]
OK so from what you're saying, I would say AsciiDoc README only so we don't maintain two file. WDYT?

**Comment by mojavelinux** [comment]
Let's do it!

**Comment by hsablonniere** [comment]
I changed the generated README into AsciiDoc in https://github.com/bespokejs/generator-bespoke/pull/38/commits/cee1e091db08965774664d2a843b88f3fe388596 in #38.

**Comment by mojavelinux** [comment]
:+1:
