### ISSUE TITLE
Guess the repository location in package.json

### ISSUE THREAD

**Issue by strugee** [bespokejs/generator-bespoke#46]
`npm init` guesses the location of the repository when generating `package.json`. We should follow suit.

**Comment by mojavelinux** [comment]
Sounds good to me!

**Comment by mojavelinux** [comment]
Can you clarify what you mean by this? Where should the repository location go?

**Comment by strugee** [comment]
It should go in the `repository` key of the new (generated) `package.json`.

**Comment by mojavelinux** [comment]
That's what I was thinking of first. But then I realized that the folder into which the project is generated was just created in the previous step (if you're following the steps in the README), so it's very unlikely to be a git repository or have a remote. Is there another common workflow in which the project is created into an existing repository?

**Comment by strugee** [comment]
My typical workflow is to clone a repo, cd into it, and run `yo bespoke init .`

**Comment by mojavelinux** [comment]
Got it. That makes sense. Perhaps we can also add this as an alternate flow in the README, then document the benefits.

**Comment by mojavelinux** [comment]
PR sent!
