### ISSUE TITLE
Consider replacing gulp-jade with gulp-pug

### ISSUE THREAD

**Issue by gleachkr** [bespokejs/generator-bespoke#49]
From what I can tell, gulp-jade hasn't been updated since 2015, while gulp-pug is actively maintained by the pugjs crew, and has several recent bugfixes that gulp-jade is missing.

**Comment by mojavelinux** [comment]
This is actually solved in the pending PR (as well as a lot of other updates). All that remains is to merge it. Though, it may need some library updates since it has been pending for awhile.

https://github.com/bespokejs/generator-bespoke/pull/38

**Comment by mojavelinux** [comment]
This is implemented in 3.0.0.
